### ISSUE TITLE
Zeta scan in NCR

### ISSUE THREAD

**Issue by xgoofyx** [Northfear/fallout2-ce-vita#11]
Hello! Enlightened One (https://fallout.fandom.com/wiki/Enlightened_One) in NCR gets a black screen on Zeta scan (the game doesn't crash, just a black screen).

**Comment by Northfear** [comment]
Hey. Could you drop me a reproducible savegame please?

**Comment by xgoofyx** [comment]
Oh sure. It is necessary in the dialogue with Enlightened One to choose the options that lead to Zeta scan.

[SLOT09.zip](https://github.com/Northfear/fallout2-ce-vita/files/9298337/SLOT09.zip)

**Comment by Northfear** [comment]
This was fixed upstream. Check the latest dev build

**Comment by mafezzz** [comment]
Is it the 1.03 build? cause in my case it wasn't fixed(

**Comment by Northfear** [comment]
Latest development build
https://github.com/Northfear/fallout2-ce-vita/releases/tag/latest

**Comment by xgoofyx** [comment]
> Latest development build https://github.com/Northfear/fallout2-ce-vita/releases/tag/latest

Thanks, everything works now! Can you tell me when the stable build will be available?

**Comment by mafezzz** [comment]
> Latest development build https://github.com/Northfear/fallout2-ce-vita/releases/tag/latest

Thank you a lot! It finally works

**Comment by Northfear** [comment]
> Thanks, everything works now! Can you tell me when the stable build will be available?

I'm keeping releases in sync with the original project, so no idea really.
