### ISSUE TITLE
Fade to black dialogue remains in black screen indefinitely

### ISSUE THREAD

**Issue by jangsohyusig** [Northfear/fallout2-ce-vita#12]
When there's a dialogue that fades to black, it stays in a black screen indefinitely. I can hear the music and the FPS counter plugin still changes, so the game is running. This problem happened on Miria/Davin's sleep option and when talking to Valerie in Vault City with Vic as a companion. So I figure, all dialogue that fades to black are affected.

Having Vic wait triggers Valerie's tool missing quest, but obviously the game treats it as if Vic isn't standing next to Valerie.  

I'm using a Vita 2000 overclocked with lolita444, playing the newest development build, and used Cheatboy in this playthrough.
[SLOT10.zip](https://github.com/Northfear/fallout2-ce-vita/files/9305984/SLOT10.zip)

**Comment by Northfear** [comment]
I suspect this is related to
https://github.com/Northfear/fallout2-ce-vita/issues/11
BTW if the issue is not only Vita related (can be reproduced on PC build too), it's probably better to create an issue on the page of the original project (https://github.com/alexbatalov/fallout2-ce)
