### ISSUE TITLE
NO ISSUES !

### ISSUE THREAD

**Issue by WastelandBoy** [Northfear/fallout2-ce-vita#15]
On my way to finish this masterpiece  on PS VITA I have encountered no issues at all!
 I did any kind of quest and sub quests on The Den, Klamath, Vault City, Gecko, New Reno and now I'm on my way to Modoc.

Sometimes crashes during loading times or  transition screens but it doesn't affect too much the gameplay experience. The game itself already running better than a lot of Vita Games.. Just remember to save before any transition screen!

I just want to say thank you again Northfear and to the team behind Fallout 2 CE.

I will update this post when I finish the game (i hope not too soon cus the game is too good 😊!)
![fallout2](https://user-images.githubusercontent.com/110431221/185747822-cf74eb94-7a17-4915-90a9-8057afb6ee7a.png)

**Comment by jangsohyusig** [comment]
Did you not have any slowdowns or lags on New Reno? I often get one there, I'm even overclocked to 500MHz.

**Comment by WastelandBoy** [comment]
I encountered some slow down on Vault City but not in New Reno. 

However I use not to play for so long, just about 1/2 hours and then I close the game, delete the old saves as Northfear recomend, and then starting the game again. 
I believe that help to play the game.

**Comment by jangsohyusig** [comment]
> I encountered some slowdown on Vault City but not in New Reno.
> 
> However I use not to play for so long, just about 1 or 2 hours and then I close the game, delete the old saves as Northfear recomend, and then starting the game again. I believe that help to play better the game.

What's your resolution and do you have overclock, if any?

**Comment by WastelandBoy** [comment]
My resolution is 848x480 and Brightness at minimum (Way better for those tiny letters)

And Yes, I use Overclock always and for everything. (3 years already!)
I use the plugin Lolita500, here's the description:
"Sets all clocks to max (including 500mhz for CPU) at all times and disables power limits like high brightness and Wi-Fi not working on intensive games."

**Comment by jangsohyusig** [comment]
> My resolution is 848x480 and Brightness at minimum (Way better for those tiny letters)
> 
> And Yes, I use Overclock always and for everything. (3 years already!) I use the plugin Lolita500, here's the description: "Sets all clocks to max (including 500mhz for CPU) at all times and disables power limits like high brightness and Wi-Fi not working on intensive games."

Thank you! Will try your settings!

**Comment by WastelandBoy** [comment]
If you have hard time with those tiny letters Try this too:
Instal the plugin Vitabright and put the brightness level on your PS VITA to maximum and then in game settings put it at minimum. In that way (and somehow) for more contrast. You gonna see better the green of the letters..

(Sorry for my bad English btw)

**Comment by Zolrex** [comment]
would be cool if port will support mod "restoration pack" with it game,even more awesome.

Yeah keep inform here about your journey,it's usefull info.
Don't forget to use latest version of port.

**Comment by jangsohyusig** [comment]
> If you have hard time with those tiny letters Try this too: Instal the plugin Vitabright and put the brightness level on your PS VITA to maximum and then in game settings put it at minimum. In that way (and somehow) is gonna be more contrast and You gonna see better the green of the letters..
> 
> (Sorry for my bad English btw)

Your English is not bad at all, and really appreciate the additional tip, thank you.

**Comment by jangsohyusig** [comment]
> would be cool if port will support mod "restoration pack" with it game,even more awesome.
> 
> Yeah keep inform here about your journey,it's usefull info. Don't forget to use latest version of port.

We'll need to wait for the original project to support that, and if that ever happens my Vita probably will be just a portable Fallout 2 machine lol

**Comment by WastelandBoy** [comment]
> 

Mine is already a fallout 2 machine 😅..
It feel so good playing on PS VITA... I have the game on Android and Even if the loading times are way better I prefer playing on Vita (Way more comfortable and immersive!)

**Comment by WastelandBoy** [comment]
> would be cool if port will support mod "restoration pack" with it game,even more awesome.
> 
> Yeah keep inform here about your journey,it's usefull info. Don't forget to use latest version of port.

Yes i will!

**Comment by Northfear** [comment]
@WastelandBoy I'm glad that you're having a blast. Let me know if you're having any issues. Most of the critical ones were fixed thanks to your report guys.

Were the slowdowns reproducible or were they gone after the game restart btw? I think I've seen one slowdown in Broken Hills, but I couldn't reproduce it again after restarting the game.

**Comment by WastelandBoy** [comment]
You right, when you restart the game the slowdowns seems to disappear. 
It happens to me in Vault City.

**Comment by WastelandBoy** [comment]
About some "issues" that I read some People report (like an npc doesn't fallow you) just remember that you need to have a good charisma (at least 6) if not some npc, animals, etc... Couldn't fallow you.
