### ISSUE TITLE
issue with C2-12828-1 in the game

### ISSUE THREAD

**Issue by Benjmoulot** [Northfear/fallout2-ce-vita#17]
Hi, 
That's so cool to play fallout 2 on ps vita!
Thank to you for your amazing job.
But just after the cave, when i begin to speak to the old women , the game often crash.
Not at the same moment everytime. 
Here the description of the crash : 

Exception Data abort exception
Thread ID 0x4001015D
Thread name SDLAudioP2
EPC fallout2-ce+ 0x0019f020
Cause 0x00030004
BadVAddr 0x00020f2C

I don't know if it could help you.
I m very bad in programmation...

**Comment by Northfear** [comment]
What version are you using? Try the latest development one. There was one with pretty frequent crashes, but they're much less common now

**Comment by Benjmoulot** [comment]
Thanks to answer.
The version i use is the latest 1.03. 
I buy the game on steam, in french version. I try to change the langage in the .config but i have the same issue in english.
The bug is totally imprevisible but it seems to have more chance to appear during a dialog with a npc with animation.
But sometime i have it in the launch of the game ( not frequent) and between two map during the loading.
Thanks to you, at this time i play like this, and i make a lot of savegame !

**Comment by WastelandBoy** [comment]
If you want the game in French search the traduction patch and put the files on the game folder on PS VITA. Overwrite if necessary.

For the Crashes as Northfear say use the latest Developer vpk and use only the files that are necessary to run the game, you can see what files you need in the the GitHub page.

**Comment by Benjmoulot** [comment]
Hi Wastelanboy,
Thanks for the recommendation and your help.
I think i have done all you say except thé overclocking.
I will try that. It s so nice to discover a second Time thé game 25 years later...i m an old geek nos!

**Comment by WastelandBoy** [comment]
You welcome my friend, enjoy as i do it right now.

**Comment by Northfear** [comment]
Should be fixed now
https://github.com/Northfear/fallout2-ce-vita/releases/tag/v1.3.0-vita.8
