### ISSUE TITLE
Getting an instant crash after start

### ISSUE THREAD

**Issue by Sergorov** [Northfear/fallout2-ce-vita#2]
Instantly crashes after startup. I get the FO2 title image, a flash of the "please stand by" screen and zap. 

What I tried: 
- I uninstalled, re-downloaded and re-installed the VPK
- deleted and re-copied the files 
- I did both a couple of times, following the same procedure as indicated in the instructuions

but nothing. It just doesn't work. Did I miss something?

Some Specs:
I'm using a PS Vita PCH1004, Henkaku 3.65. The game version I used was the unmodified "fresh" install of Fallout 2 from steam.

**Comment by Northfear** [comment]
Try using the latest development build:
https://github.com/Northfear/fallout2-ce-vita/releases/tag/latest
And installing ONLY the files (master.dat, critter.dat, patch000.dat, data and sound folders) that were mentioned in README (no ini files, etc). And let me know in case this won't help. Could be the problem with 3.65 (I've only tested with 3.60)

**Comment by Sergorov** [comment]
Hello! Thank you for the quick reply. I installed the latest build, but it still crashes the same way as before. I only copied the exact files and folders mentioned in the readme. The only additional file (that appears when I first try to run the app) is the f2_res.ini, which is just storing the resolution I believe. Could it be an issue with the language? I installed the German language version (or rather: Steam did).

**Comment by Sergorov** [comment]
I tested this, and apparently the english version works! I'll see which file exactly is causing this, as I would love to let my youngster play this, but he doesn't know english yet. So would be cool if it would work for the German version as well. One peculiar thing I also noticed is that tha .dat files are for some reason spelled uppercase in the German language version. So master.dat is MASTER.DAT. Not sure if it's just that little nuance in spelling that prevents the files from being found. I'll test this and let you know!

**Comment by Sergorov** [comment]
OK, I my tests have shown the following results:
- I can replace every file and folder with the version from the German install except for one: master.dat (not entirely unexpected)
- the uppercase is not the problem, the english MASTER.DAT will still work, the German master.dat will still fail
- Unfortunately he language is obviously coded into the master.dat, so all German install files with the english master.dat will still result in an english game.

Conclusion: Please please please can you make the German master.dat work? 
Let me know if I can do anything to help!

**Comment by Northfear** [comment]
You can ask about German version support at the page of the original project
https://github.com/alexbatalov/fallout2-ce
The project was build upon original US version in mind and other languages were not de-compiled yet.

**Comment by Sergorov** [comment]
Thanks for the tip! I'll try my luck there.

**Comment by Sergorov** [comment]
Update:
It works! If you have installed a translated version all you need to do is to **copy your fallout2.cfg** along with the master.dat, critter.dat, update000.dat, data folder and sound folder. It seems to be imported along with the other files automatically. This also works for the android version! I have played a couple of minutes and didn't encounter any issues so far, and everything is translated! This is confirmed working for the Steam version and apparently also for the GOG-version (a user of the French translation of the GOG version gave me the tip). You might want to include that in the instructions.

**Comment by Northfear** [comment]
Huh, that's interesting. Mind sharing fallout2.cfg?
I suspect that there is some langue related function out there

**Comment by Sergorov** [comment]
Not at all! The "secret" is in line 55, where it says language=german (can be language=english or language=french, depending on which language version you have installed). I attached the file renamed to .txt, as it seems .cfg files are not supported.
[fallout2.txt](https://github.com/Northfear/fallout2-ce-vita/files/9263181/fallout2.txt)
.
