### ISSUE TITLE
On board controls

### ISSUE THREAD

**Issue by Arielsicx** [Northfear/fallout2-ce-vita#21]
I can’t get the vitas onboard controller to work in the game only the touchscreen works.

**Comment by Northfear** [comment]
That's weird. My guess is that there's probably some plugin compatibility issues.
Are you talking about handheld Vita? Onboard controller, not external one, right?

**Comment by Arielsicx** [comment]
Yes handheld vita

**Comment by Arielsicx** [comment]
On board controller not external controller. Although I do have the ps4 controller driver for vita installed. I haven’t tried using that yet.

**Comment by Northfear** [comment]
What do you mean by "ps4 controller driver"? ds4vita? Have you tried disabling it?

**Comment by Arielsicx** [comment]
I tried disabling it once I will try again when I get the time

**Comment by Arielsicx** [comment]
Still doesn’t work

**Comment by Northfear** [comment]
Could you send a list of installed plugins? I'm trying to find a way to reproduce this one

**Comment by Arielsicx** [comment]
I figured it out. It was a plug-in that allows 4 players to play on one handheld vita
