### ISSUE TITLE
World map hiding the town map when entering a location

### ISSUE THREAD

**Issue by zachary-cauchi** [Northfear/fallout2-ce-vita#23]
Hi Northfear.

I'm experiencing an error with the world map when exiting any location and then entering any location where once I'm going into a location/town and have the option of selecting a marker to spawn in, the markers are visible, but the worldmap remains visible and covers the town map. When hovering over the marker, it would flash the town map for a frame then go back to the worldmap. Once a marker is chosen, the world map fades out and I spawn into the location without further glitches. So far, noticed it when exiting/entering the raider camp, Broken Hills, and New Reno. I'm using the latest development build (60ef02f). If there's any further information I can provide, let me know. Thanks

**Comment by Northfear** [comment]
Hey. Could you drop a savegame please. so I could try reproducing it quickly?

**Comment by rhorschack** [comment]
Encountered the exact same problem which is not present on previous versions.

**Comment by Northfear** [comment]
Ok, I've updated the vita version with the latest development one and removed world map scrolling hack. You can give it a go
https://github.com/Northfear/fallout2-ce-vita/releases/tag/latest
