### ISSUE TITLE
Fallout Sonora boot crash

### ISSUE THREAD

**Issue by DvaMishkiLapa** [Northfear/fallout2-ce-vita#24]
Good afternoon!

I tried to run the [latest official original version of Fallout Sonora](http://fallout-nevada.ucoz.ru/index/opisanie_fallout_sonora/0-59), but after starting the application automatically closes.

I saw that the original project supports this modification (https://github.com/alexbatalov/fallout2-ce/issues/249). Is there any solution to this problem?

[I use the latest version from the CI autobuilder.](https://github.com/Northfear/fallout2-ce-vita/releases/tag/latest)

**Comment by DvaMishkiLapa** [comment]
I forgot to mention, the Sonora files directory was placed in `ux0/data/fallout2` with the following contents.
![sonora](https://github.com/Northfear/fallout2-ce-vita/assets/18528109/302f82c1-19cf-4978-8eda-77521bde4985)

**Comment by DvaMishkiLapa** [comment]
If there's anything I can do to help, I'd be happy to do it.
I have VitaSDK, but I couldn't find any Debug mode in your program.

**Comment by Northfear** [comment]
You can actually. Can you upload the mod itself somewhere? [Оригинальная авторская версия 1.10c](https://cloud.mail.ru/public/rgAk/v5kYSB2Fe)
I got no access to mail.ru here and downloading it with some free VPN would take forever.

**Comment by DvaMishkiLapa** [comment]
I posted the archive on [Mega.nz](https://mega.nz/file/WgwSHTib#bmjFheinbnaWNH7YLTUGNcSEGWBIclwe9aEHeV2gDac).

It has a good speed and seems to be available everywhere.

**Comment by Northfear** [comment]
Should be fixed now
https://github.com/Northfear/fallout2-ce-vita/releases/tag/latest
Default `art_cache_size` value was 512 in the config file (which was way too much for Vita to handle).
