### ISSUE TITLE
Unavoidable crash fighting Cameron

### ISSUE THREAD

**Issue by BigDeal716** [Northfear/fallout2-ce-vita#26]
In the Temple at the beginning of the game I experienced 13 crashes
1 crash while dropping the bomb at the metal door
2 normal crashes while loading a save

and 10 unavoidable crashes while fighting Cameron.

To recreate 
1. Begin talking to Cameron and exhaust all of his dialogue.
2. begin battle with Cameron as normal.
3. fight until he is “severely wounded”
4. When im assuming he is supposed to stop the fight the game crashes (i just tested again to make sure and it crashed at the exact spot for the 11th time)

To attempt to fix this I’ve uninstalled the VPK and all of the data and reinstalled it multiple times as well as copied over fresh Fo2 data each time, and uninstalled and reinstalled Fo2 on my PC.
Ive also downloaded the VPK from multiple sources (github, BHBB, Vita DB Downloader) as well to make sure it was not a broken download.

(SAVEDATA)
[savedata.zip](https://github.com/Northfear/fallout2-ce-vita/files/13624247/savedata.zip)

**Comment by BigDeal716** [comment]
Ive started a completely new game with a freshly installed VPK from the github release as well as new game file’s newly installed on a different PC and the problem still persist in the exact same place. As soon as the fight with Cameron is supposed to finish the game crashes, ive tested it with an additional 4 more crashes in the same exact place back to back, i can’t proceed with the game.

**Comment by BigDeal716** [comment]
https://www.reddit.com/r/VitaPiracy/s/JkCSCJLqOQ

Found someone else with the same problem as well

**Comment by Northfear** [comment]
Ok. That's weird, but I can't really reproduce it
Could you try the latest dev version please?
https://github.com/Northfear/fallout2-ce-vita/releases/tag/latest

**Comment by BigDeal716** [comment]
I was able able to beat cameron with the dev build

i was also getting a crash every time i tried to go to the Den, im going to test that out as well

**Comment by BigDeal716** [comment]
> i was also getting a crash every time i tried to go to the Den, im going to test that out as well

Im not getting the crash when trying to enter Den anymore either on the Dev build

**Comment by Northfear** [comment]
Nice. I'll update vitadb version today. Thanks for reporting
