### ISSUE TITLE
f2_res.ini and freezes

### ISSUE THREAD

**Issue by oT2** [Northfear/fallout2-ce-vita#27]
Hello, 

I am starting a F2 run using your port and it is great, but i face an issue where my game will freeze regularily for a few seconds. 

I have vanilla version+ child patch, and I play in french.

Doing some research I realized that f2_res.ini never got created, any idea how I can regen it or where i can find a template of it ? Maybe it is related.

Thank you

**Comment by oT2** [comment]
I just realised I am also missing ddraw.ini .

From my understanding both files should have been generated by the game as it is not instructed to copy it.

No idea if my game getting freezes after changing location a few times is related to this.

**Comment by oT2** [comment]
I re installed game files without any patches and the freezes seem to be gone.

Still no f2_res.ini or ddraw.ini, but i noticed that if I create it myself following fallout2-ce's readme it works so all good I guess.

Thank you for your work !

**Comment by Northfear** [comment]
Haha. Glad that you figured it out

Freezes might be due to the slow Vita IO. If there's more than ~100 files in one folder (which is often the case with those patches), all of the operations with them are becoming increasingly slow. So you probably have to be careful with patches/mods
