### ISSUE TITLE
IFace Bar size

### ISSUE THREAD

**Issue by WastelandBoy** [Northfear/fallout2-ce-vita#4]
I wonder if there's a way to enlarge the Interface bar to fit the screen like I use on PC.

And by the way thank you so much to let us play this wonderful game on PS VITA!

[Fallout2CE](https://user-images.githubusercontent.com/110431221/182952593-97838bfb-654b-463c-95ed-f4dbb5102ef5.jpg)

**Comment by Northfear** [comment]
Not yet. There's only basic support for high resolution mod for now, so any kind of enlargement/additional graphics are not supported yet.
If you're interested about details about its support - the page of the original project is probably the right place to go
https://github.com/alexbatalov/fallout2-ce

**Comment by WastelandBoy** [comment]
To be honest the game run really well on PS VITA.
The Vita's native resolution is just perfect for this game (960x544). But the Fonts are very small and make it hard for play the game for long time.

Anyway let's see if it's possible , I'm gonna keep an eye on that page.

Thanks so much for your hard work!

**Comment by WastelandBoy** [comment]
And now the Interface bar has no sides and the Fonts are a little more big!
I just change the way of view the IFace Bar from the f2_res.ini 
I put that line because it wasn't there.
![fallout2_848x480~3](https://user-images.githubusercontent.com/110431221/183255020-96bced39-6aca-4604-8efc-cff1e738620f.jpg)

**Comment by Northfear** [comment]
Looks nice. What did you add exactly into f2_res.ini? I might add it as default setting in the next release

**Comment by WastelandBoy** [comment]
848x480 and the option for the iface bar activated. 

Looks and play just great!
Again, thanks so much for this wonderful game!

![IMG_20220806_153729](https://user-images.githubusercontent.com/110431221/183263898-b13ac82a-78a0-42cf-96e9-fa586ebe4e98.jpg)

**Comment by CD4NV** [comment]
> 848x480 and the option for the iface bar activated.

Could you attach your f2_res.ini file to this post for study. Thank you in advance.

**Comment by WastelandBoy** [comment]
Of course!
[f2_res.zip](https://github.com/Northfear/fallout2-ce-vita/files/9277155/f2_res.zip)

**Comment by CD4NV** [comment]
> Of course! [f2_res.zip](https://github.com/Northfear/fallout2-ce-vita/files/9277155/f2_res.zip)

Thx a Lot

**Comment by Northfear** [comment]
Only ```IFACE_BAR_MODE```, ```SCR_WIDTH``` and ```SCR_HEIGHT``` from the list of HiRes mod options are functional in Fallout 2 CE currently.
I've also set IFACE_BAR_MODE to 1 by default. Thanks for the tip @WastelandBoy. It looks really nice.

**Comment by WastelandBoy** [comment]
So i have the game on my Nokia X100 wich is supposed to be More powerful than my PS VITA but still I enjoy the game more on my Vita. It's just more comfortable and looks even better..
Plus the Vita Screen is the perfect fit (960x544).

For me, the PS VITA is the best way to play this games on the Go hands down and is all because of you guys!

THANKS SO MUCH Northfear and all the people behind this wonderful project.

PS.
And 
![Fallout2_PSVITA_848x480](https://user-images.githubusercontent.com/110431221/183962343-3e6b042f-f298-4d4b-85a9-23e1a7dfcd70.jpg)
Please give me a link where I can support your work $!
