### ISSUE TITLE
you can't interact with npc animals from quests

### ISSUE THREAD

**Issue by rodrigoxmax** [Northfear/fallout2-ce-vita#5]
for example the mission of the intelligent scorpion you cannot interact with it and it only tells you that you have seen a scorpion

**Comment by Northfear** [comment]
Hey. Drop me a reproducible savegame. If this can be reproduced on PC version too, you can create an issue on the original page
https://github.com/alexbatalov/fallout2-ce

**Comment by Northfear** [comment]
This was fixed upstream. Check the latest dev build

**Comment by rodrigoxmax** [comment]
Thank you. but I wait when the version is finished
