### ISSUE TITLE
Screensaver in PipBoy

### ISSUE THREAD

**Issue by CD4NV** [Northfear/fallout2-ce-vita#8]
Port Version: PS Vita Development Build (Latest Release).
If the player opens a pip fight and does not do anything in it, then after a while the screensaver in the form of falling atomic bombs will begin.
In the port, after waiting, the screen on the right simply goes out, while there are no falling atomic bombs.
P.S.: This is certainly not quite a bug, but would like this port to be as authentic as possible to the original of the game.
P.P.S.: In the win version, the screensaver works.

**Comment by Northfear** [comment]
Fixed in the latest release
